### ISSUE TITLE
Max connector output and input limited to 80000 FE/t

### ISSUE THREAD

**Issue by l0py2** [mrh0/createaddition#905]
**Describe the bug**

**Modified configuration properties**
createaddition-common.toml:
```toml
[wires]
  small_connector_max_output = 128000
  small_connector_max_input = 128000
  connector_allow_passive_io = false
  large_connector_max_input = 128000
  large_connector_max_output = 128000
```

**To Reproduce**
- Place an [Energy Meter](https://www.curseforge.com/minecraft/mc-mods/energymeter)
- Configure Energy Meter mode to Consumer
- Configure top face to input
- Place an Creative Generator
- Connect the Creative Generator with the Energy Meter using any connector
- The energy meter reads 80.0 kFE/t

**Additional context**
- Mod version: 1.20.1-1.3.0
- Forge version: 47.4.0
- Create version: 6.0.2
- [Energy Meter](https://www.curseforge.com/minecraft/mc-mods/energymeter) version: 1.20.1-1.0.0

![Example](https://github.com/user-attachments/assets/5e0b6530-38c6-4076-9f7c-64f3aecef06e)
